FROM alpine:latest
RUN apk add --no-cache --update bash build-base coreutils gcc libffi-dev musl-dev python3 python3-dev
RUN apk add openssl openssl-dev
RUN apk add py3-setuptools
RUN pip3 install sovereign

ADD templates /etc/sovereign/templates
ADD config.yaml /etc/sovereign/config.yaml
ENV SOVEREIGN_CONFIG=file:///etc/sovereign/config.yaml

EXPOSE 8080
CMD sovereign