version: '2.3'

services:
  sovereign:
    container_name: sovereign
    build:
      context: .
      dockerfile: Dockerfile.sovereign
    environment:
      SOVEREIGN_HOST: '0.0.0.0'
      SOVEREIGN_PORT: '8080'
      SOVEREIGN_DEBUG: 'yes'
      SOVEREIGN_ENVIRONMENT_TYPE: local
      SOVEREIGN_CONFIG: file:///etc/sovereign/config.yaml
    ports:
      - 80:8080
    expose:
      - 80

  envoy:
    container_name: envoy
    build:
      context: .
      dockerfile: Dockerfile.envoy
    links:
      - sovereign
    expose:
      - 9901